[project]
    name = "zhTW-pdf-collector"
    version = "0.1.0"
    description = "蒐集台灣公開資訊 PDF"
    requires-python = ">=3.12"
    dependencies = [
        "requests",
        "beautifulsoup4",
        "selenium",
    ]